version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django-backend
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080
    env_file:
      - backend/.env

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  
